# Generated by Django 5.1.4 on 2025-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
