# Generated by Django 5.1.4 on 2025-05-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_listing_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='completed',
        ),
    ]
